name: build

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    branches: [ 'master' ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

env:
  COMPOSE_PROJECT_NAME: yii2-queue
  COMPOSE_FILE: tests/docker-compose.yml
  AWS_SQS_ENABLED: ${{ secrets.AWS_SQS_ENABLED }}
  AWS_SQS_URL: ${{ secrets.AWS_SQS_URL }}
  AWS_KEY: ${{ secrets.AWS_KEY }}
  AWS_SECRET: ${{ secrets.AWS_SECRET }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SQS_FIFO_ENABLED: ${{ secrets.AWS_SQS_FIFO_ENABLED }}
  AWS_SQS_FIFO_URL: ${{ secrets.AWS_SQS_FIFO_URL }}
  AWS_SQS_FIFO_MESSAGE_GROUP_ID: ${{ secrets.AWS_SQS_FIFO_MESSAGE_GROUP_ID }}
jobs:
  phpunit:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PHP Unit tests for PHP ${{ matrix.php }}
        run: make test v=${{ matrix.php }}
