on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'UPGRADE.md'
      - '.gitignore'
      - '.gitattributes'
      - 'phpunit.xml.dist'

  push:
    branches: [ 'master' ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'UPGRADE.md'
      - '.gitignore'
      - '.gitattributes'
      - 'phpunit.xml.dist'

name: static analysis

env:
  COMPOSE_PROJECT_NAME: yii2-queue
  COMPOSE_FILE: tests/docker-compose.yml
jobs:
  psalm:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2' ]
    steps:
      - name: Checkout.
        uses: actions/checkout@v2

      - name: Run static analyzes for PHP ${{ matrix.php }}
        run: make static-analyze v=${{ matrix.php }}
